### ISSUE TITLE
[SW]  C lenguage style

### ISSUE THREAD

**Issue by mfrata** [floripasat/obdh#10]
Qual padrão de codificação que vamos usar no SW?
MISRA, NASA-C, Indian Hill, outra?

Importante decidir isso para colocar na documentação de SW

**Comment by eldertramontin** [comment]
Vamos usar o NASA-C style, com modificações.
A princípio a única mudança é na utilização da "{" na mesma linha, e não na linha seguinte a chamada de função / definição de struct / etc.
Posteriormente podemos fazer mais algumas alterações. A referência do nosso estilo de codificação pode ser gerada em: http://www.rosvall.ie/cgi-bin/genCodeStd.pl
Vou atribuir esta issue para mim, deixando em aberto a tarefa de alterar o código atual para atender a esta decisão.
