### ISSUE TITLE
Store the antennas deployment status on non-volatile memory

### ISSUE THREAD

**Issue by eldertramontin** [floripasat/obdh#104]
In case of communication failure, the OBDH must be able to know if the deployment was already done.

**Comment by mariobaldini** [comment]
Quando gravar esta info, use bits redundantes. 
Por ex: 
Ao invés de usar 1 byte, com dois possíveis valores; use 3 e considere o valor da maioria. Assim se um for corrompido, vc ainda chega no status correto. 

E cuidado quando fizer IFs/Switches de comparação para não esperar que as únicas opções sejam as previstas originalmente. 
Ex:
0xAA - deployed
0xBB - não deployed

pode ocorrer um bitflip e vc ler depois 0xCC; 
se isto não estiver previsto adequadamente na compração, não vai entrar em nenhum dos estados e talvez gerar algum bug.
