### ISSUE TITLE
Analyze OBDH / TTC Transceiver communication procedure

### ISSUE THREAD

**Issue by eldertramontin** [floripasat/obdh#17]
Just establish communication with the radio module (RF4463), over SPI.

**Comment by mariobaldini** [comment]
Uma dica: quando se encerra a issue é bom ter um comentário: se foi feita
com sucesso, se não vai mais ser feita pq saiu do escopo, não é
tecnicamente viável, etc.

Vi q varias foram fechadas, mas vendo o projeto de fora, não tenho como
saber se a issue X foi implementado e fechada; ou simplesmente ignorada e
fechada.

É importante pro futuro caso alguém queira olhar a documentação pq entrou
no mesmo problema.
