### ISSUE TITLE
SPI send

### ISSUE THREAD

**Issue by eldertramontin** [floripasat/obdh#38]
Create a SPI send function that send a byte.

**Comment by mariobaldini** [comment]
Isso aqui não está implementado ainda?

**Comment by mfrata** [comment]
Ele tem um library de SPI apenas com o cartão SD. Código que ele não vai mudar para nao quebrar o do cartão.

A proposta é fazer um drive mesmo, com no minimo as funções read, write e config.

Acho melhor deixar essa aqui pro arthur(carinha novo) que esta aprendendo spi no momento.
