### ISSUE TITLE
Send Internal sensors data to the store data task

### ISSUE THREAD

**Issue by eldertramontin** [floripasat/obdh#46]
Send temperature, voltage and current through a queue.

**Comment by mariobaldini** [comment]
Já existe uma task que lê periodicamente valores de sensores (ex: temperatura, corrente, etc..) e salva na memória nv?

**Comment by eldertramontin** [comment]
Sim. Uma task lê os sensores e envia os dados a outra task que salva na memória não volátil.

**Comment by mariobaldini** [comment]
Onde está documentado o formato de como esses dados são salvos na memória? (e como extrair/decodificar eles)

**Comment by eldertramontin** [comment]
Não está. Vou verificar onde é melhor para documentar isso, criar uma issue referente e linkar assim que o fizer.

**Comment by mariobaldini** [comment]
Blz.

Mas a documentação sempre tem q fazer parte da atividade em si. Organização e documentação do projeto tem mais importância do que código fonte em si (do primeiro é mais fácil chegar no segundo; do que o contrario).

Quando resolver uma issue, está implicito que o resultado foi propriamente documentado. Caso não tiver sido feito ainda, pode deixar pendente na propria issue (e não fechá-la ainda).

**Comment by eldertramontin** [comment]
https://github.com/floripasat/obdh/blob/master/firmware/docs/packet_description.md#msp-sensors
