### ISSUE TITLE
Read MSP430 internal temperature

### ISSUE THREAD

**Issue by eldertramontin** [floripasat/obdh#48]
Read the internal temperature sensor of MSP430F6659.

**Comment by mfrata** [comment]
Eu coloquei ele na SPI. As memorias que trouxemos depois do cartão SD ainda não tem **nada** de código. 

A principio estava falando com o Elder para deixar o SD para dados e a memoria para coisas auxiliares como log de telecommandos ou constantes para outros fins. 

Portanto concordo com:

Documentar
Fazer testes 
revisar o código e commitar no dev (elder revisa e depois passa pro master)

só que para o SPI e não para o ADC
