### ISSUE TITLE
First boot information

### ISSUE THREAD

**Issue by eldertramontin** [floripasat/obdh#49]
Title;
Firmware version;
Hardware version;
Modules tests (clocks info, spi config info, i2c config info,etc) ;
"Boot completed"

**Comment by mariobaldini** [comment]
Validar e fazer o merge no master

**Comment by eldertramontin** [comment]
"Modules tests (clocks info, spi config info, i2c config info,etc) ;" 
changed to:
"MSP peripheral tests (clocks) and setup info(clocks, uart, spi, i2c and adc) ;" 

Modules tests will be splitted in new issues.
