### ISSUE TITLE
Implementar a resposta a comandos de debug

### ISSUE THREAD

**Issue by eldertramontin** [floripasat/obdh#50]
Answer a command with a information:
COMMAND      |        RESPONSE
v                       |       OBDH voltage                      
i                        |        OBDH current
t                        |       temperature
s                       |       systick

**Comment by mariobaldini** [comment]
Os titulos das issues devem ser mais objetivos e associados com o bug/feat q será implementado em si (ie. primeira linha da commit msg). 

Neste, por exemplo, nao dá pra entender se a issue é "requisitar a info de alguém",
ou implementar um comando q requisita alguma info

Reescreve o titulo e descrição pq nao consegui entender
