### ISSUE TITLE
Update git README.md with proper pointers to the official docummentation

### ISSUE THREAD

**Issue by mariobaldini** [floripasat/obdh#54]
Official OBDH docs (full detail) are stored in gdrive? 

Insert a link into the readme, so a developer can easily go directly to the proper document and fix/review a documentation issue.

**Comment by mfrata** [comment]
Ainda não movi para o drive.

Quero terminar de soldar pelo menos duas placas para o pessoal do SW ter hardware. Por enquanto vou colocar o link para o gitbooks

**Comment by mariobaldini** [comment]
Nem coloca pro gitbooks. Ele já foi 'descontinuado' né? 

Se sim, não vale gastar tempo com algo q vai ser morto. Já coloca direto por oficial.

**Comment by mfrata** [comment]
Ja existe um ponteiro para la. Quando eu fizer mudança faço o commit e ja fecho essa issue
