### ISSUE TITLE
Minimal Assembly PCB 2

### ISSUE THREAD

**Issue by mfrata** [floripasat/obdh#59]
Soldering and tests of steps 1 to 16 described here: goo.gl/nFI1Of

**Comment by mariobaldini** [comment]
Poderia revisar que placas estão sendo montadas? 

As 3 q foram feitas em janeiro são a versão 2.0? (uma das que tenho aqui comigo).
e que tinham alguns bugs. 

Os bugs foram corrigidos e agora em Março fabricadas as versões 2.1?

**Comment by mfrata** [comment]
A versão 2.0 teve duas placas montadas. A que tu levou e a que o Elder ficou mexendo.

No momento estou montando as  da versão 2.1. Que tinha aqueles bugs "corrigidos". 
Só vou ter certeza de que foram corrigidos depois que soldar tudo e fazer os testes minimos.

**Comment by mfrata** [comment]
Devido a ISSUE PCB 2 - SPI1 Bus Bug #68 esta será fechada
