### ISSUE TITLE
CCS v7.1 7.1.0.00015 incompatibility

### ISSUE THREAD

**Issue by mariobaldini** [floripasat/obdh#63]
Error while importing project. 

``
Error: Import failed for project 'obdh' because its compiler definition is not available. Please install the MSP430v16.6 compiler before importing this project - click 'View > CCS App Center' to check if compiler updates are available, or install the compiler manually and register it with CCS through 'Preferences > CCS > Build > Compilers'.
``

**Comment by eldertramontin** [comment]
A versão usada do CCS é a 6.1.3.00034. Está sendo usada esta versão para evitar problemas com diferentes versões. Podemos migrar todo o código para uma mais atual, porém será necessário refazer a validação de todo o software.

Para configurar a toolchain, siga este tutorial:
https://github.com/floripasat/obdh/blob/master/firmware/docs/toolchain_setup.txt

**Comment by mariobaldini** [comment]
Já estou migrando aqui. (falta alguns testes), mas a principio não teve erro de compatibilidade. 

Faz mais sentido já migrar pro CCSv7, especialmente pq o novo compilador da TI tem bugfixed e é uma versão LTS. TI v16.9.1 LTS

A versão anterior não era LTS, então é melhor fazer toda a validação em uma long term
