### ISSUE TITLE
clock stabilization time is longer then expected

### ISSUE THREAD

**Issue by eldertramontin** [floripasat/obdh#64]
The wait time until the clock be stable is shorter then necessary. It is necessary add a longer delay (few seconds).

**Comment by mariobaldini** [comment]
Poderia explicar um pouco mais?


Sobre o titulo, este ai está mais com cara de git commit, pois ele 'corrige' o erro. Para issues fica mais legível se for o erro em si (pode omitir que 'é necessário corrigir'). Isso vai estar implicito por uma label de 'bug', improvement, etc.

**Comment by mariobaldini** [comment]
Mudei pra um exemplo ali do que acho q entendi. 

Aquele 'too long' ali não está bom, pq é subjetivo e não especifico. O melhor seria ter algo mais objetivo, se viável

**Comment by eldertramontin** [comment]
Modifiquei o título e a descrição. Espero que esteja mais claro. Basicamente é preciso só colocar um delay no codigo. Só criei a issue pra justificar a modificação.
